### ISSUE TITLE
Environment Parity: Migrate Helm v2 to v3 for ARGO QA and ARGO DEV

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#176]
Needed for QA cluster

- [ ] ARGO DEV 
- [ ] ARGO QA

services:
- [x] clinical
- [x] gateway
- [x] ui
- [x] lectern
- [x] donor agg
- [x] program svc
- [x] ego
- [x] mail hog
- [x] rollcall
- [x] docs
- [x] lectern db

**Comment by blabadi** [comment]
changing clinical to helm3 renamed the release name from `clinical-argo-dev` to `clinical`, faced these issues
- jenkins qa cannot create/read clusterrolebinding 
- vault role policy to service account name need update if release name changed
- network policies will need update (kafka, lectern, clinical-db, rxnormdb)

**Comment by blabadi** [comment]
gateway, lectern migrated to helm 3

**Comment by blabadi** [comment]
aggregator, ui migrated

**Comment by blabadi** [comment]
program service migration steps:

1- prepare values file
2- prepare new network policies and apply them
3- install new helm 3 release 
`helm3 install program-service argo/program-service -f values.yaml`
4- get into the postgres terminal, get sql dump inside old postgres `pg_dump -h localhost -p 5432 -U postgres program_service > /tmp/dump.sql`
5- copy that dump outside the container to your local machine `kubectl cp argo-dev/program-service-argo-dev-postgres-0:/tmp/dump.sql ~/dev/null/ps-dev-dump.sql`

6- copy the dump to the new postgres container
`kubectl cp ~/dev/null/ps-dev-dump.sql argo-dev/program-service-postgres-0:/tmp`

7- get into a terminal in the new db container, apply the dump there: 

I had to drop the existing schema since the dump contains everything.
```
psql -U postgres
drop schema public cascade;
create schema public
```
exit psql
apply the dump: `psql -U postgres -f /tmp/ps-dev-dump.sql`

8- vault needed update to the policy service account binding:
```
vault write auth/kubernetes/role/program-service-argo-qa bound_service_account_names=program-service bound_service_account_namespaces=argo-qa policies=program-service-argo-qa_policy ttl=1h
```

**Comment by andricDu** [comment]
Giving this SP:2 to aid in sprint estimates.

**Comment by rosibaj** [comment]
@blabadi i dont think theres any express testing for me to do here :) is there anything we need to do to "deploy/release" this that is not yet done?

**Comment by blabadi** [comment]
no the only testing is checking that everything still works as is, and no production / staging update required

**Comment by rosibaj** [comment]
Qa lgtm to me today - havent seen any issues at all!
