### ISSUE TITLE
Create RDPC dev environment 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#229]
to replace `farting-owl`, we need to initialize a dev space for workflows. 

- [ ] Create new  `rdpc-dev` cluster with `rdpc-dev` namespace
- [ ] it should be in `RDPC_ARGO_YUNG` tennant
- [ ] Assign 2 x 38-core machines and then maybe 8 x 16 cores for test processing

**Comment by lepsalex** [comment]
We want 2 x 38-core machines and then maybe 8 x 16 core? Too much?

**Comment by jmimico** [comment]
We will be creating the ARGO RDPC Dev environment in an *new* OpenStack project named ARGO_RDPC_Dev_Yung instead of the originally planned ARGO_RDPC_Yung (Production) project. This separation is needed so that we can better maintain access controls to the production environment and more accurate reporting.
