### ISSUE TITLE
Fix timeout strategy

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#248]
A limiting factor is CPU right now 
- We can run 40 jobs at a time, but the resources are not available 
- Executor pods spin up and try to schedule jobs with xx cpu.  that cpu will not be available for some time and the pod 
- After some amount of time, Kubernetes cancels the nextflow pod.  It should have a longer wait time and the job should not be cancel. 

## Exit Criteria 
Find the timeout config or restart policy  in Kubernetes for a pod and make sure it is set to a very long time.

**Comment by lepsalex** [comment]
From what I can tell by looking at Kubernetes docs and at the pod descriptions for Nextflow pods (both workflow and process) it appears that they are using the default Kubernetes scheduler that will attempt to schedule pods regardless of time elapsed.

We can close this ticket for now and open a new one if we encounter any specific instances of pods being terminated due to timeout (we have not yet).
