### ISSUE TITLE
UI Kit: Enhanced tabs

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#345]
- make the tabs
- color the tabs
- config the tabs 
- ENHANCE!

Zeplin: 
Primary Diagnosis active and see tab hover state (first treatment tab): https://zpl.io/V1n0ZJm
Specimen active tab: https://zpl.io/anRDrKO
Treatment active tab: https://zpl.io/VY4OJBn
Follow up active tab: https://zpl.io/bAyMGZq

**Note. In the design, if the donor is deceased the last tab is shown but it does not click to any information. it shouldn't be clickable**
<img width="278" alt="Screen Shot 2020-03-26 at 11 28 13 AM" src="https://user-images.githubusercontent.com/18424138/77664638-e77ebc00-6f54-11ea-95fe-ecd79bec8edd.png">

**Comment by kcullion** [comment]
@ciaranschutte just reviewing storybook and it looks great!: https://argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-clinicaltimeline--basic

A couple things
- [x] Can you implement the correct font (work sans) for the vertical text: Interval since diagnosis (days)
- [x] is it possible to add the commas for the days along the side to make the numbers easier to read - like 242,222 instead of 242222
- [x] Can you decrease the space between the vertical label and the days column (approx 10px space in between)
<img width="567" alt="2020-05-04_1337" src="https://user-images.githubusercontent.com/18424138/80995798-d6a34f00-8e0c-11ea-9d35-8c741adadd7f.png">

- [x] When unchecking the orange treatments checkbox, the long date disappears, making that date column width smaller. This causes the tabs to jump. Can we stick to a fixed width for that date column so that the tabs don't jump around on the page? the number likely won't be larger than 365,000 I assume :)

- [x] Did you do the last tab, if the donor is deceased? See screenshot above - if the donor is deceased the last tab is shown but it does not click to any information. it shouldn't be clickable

**Comment by ciaranschutte** [comment]
- deceased tab and vertical text font are here: https://github.com/icgc-argo/platform-ui/pull/1419

**Comment by rosibaj** [comment]
@ciaranschutte can you please add a version label tag to this ticket? Cannot release it till added.

**Comment by kcullion** [comment]
Hey @ciaranschutte did you happen to also do the empty state for this clinical timeline area? This is when a donor doesn't have any of those files uploaded yet.
https://invis.io/FES2W305M6Q#/411480154_Timeline-Empty

**Comment by rosibaj** [comment]
@kcullion its in the options: 
![image](https://user-images.githubusercontent.com/15824252/81198527-93251e00-8f8f-11ea-80fb-b5ac879f51c6.png)

**Comment by kcullion** [comment]
deleted the comment because I noticed it. thanks

**Comment by rosibaj** [comment]
oops i just answered from email :)

**Comment by kcullion** [comment]
did not know you could do that! ha!
