### ISSUE TITLE
RDPC Backup and manual restore: Replicate Collaboratory backup store to Cumulus offiste backup store

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#383]
Collab will be the short term on-site backup store for the RDPC
This will need to be synced to an off-site backup at OICR Cumulus/NFS for a longer period of retention

**Comment by akachru-github** [comment]
@henro001 , @yalturmes  I think this is already set up  right?

**Comment by akachru-github** [comment]
@jmimico , just checking in on status: is this already set up and just waiting on actual backups to be taken in Collab for RDPC services?

**Comment by jmimico** [comment]
This is not currently set up because IT was supposed to do research on improved access control of files on the isilon. Henrich said he would follow up with Bob to see what happened with the research on that.

**Comment by akachru-github** [comment]
- Set this up with our current set of backups (ETCD, Jenkins)
- Pull from the final place of rest (Pulling from Collab)

**Comment by akachru-github** [comment]
@jmimico , would you be able to help us set this up?

**Comment by jmimico** [comment]
I've set up replication of backups to pull via rsync, all backups on Collab instances argo-rdpc-mgnt /srv/kube-backup/ and argo-rdpc-dev-mgnt /srv/kube-backup to Cumulus argo-nfs-backup /srv/rdpc-backup/ and /srv/rdpc-dev-backup respectively. This runs at 10:10AM daily and will email Henro and I with a summary of what was copied. This is the same strategy we use for replicating ARGO backups to Collab. One last thing to note is that @henro001 still needs to change the location of RDPC-DEV backups to dump to argo-rdpc-dev-mgnt instead of nfs-dev-1 since this was inconsistent with how we do it for prod.
