### ISSUE TITLE
Horizontally Scale Platform-UI & backends in test env - ProgramServce

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#434]
- horizontally scale each of those service out in dev/QA to see if it causes anything

**Comment by blabadi** [comment]
updated values file in argo-infra, I haven't noticed weird behavior, however, the load balancing needs more investigation because of the GRPC connection in gateway is persistent.

the scaled up instances will get engaged when gateway reconnect to PS or when a PS instance goes down, so we can have more availability
