### ISSUE TITLE
RDPC-Production cluster: Jenkins installation

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#461]
Jenkins has been installed on the RDPC DEV / QA cluster. This ticket captures the same scope of work for the RDPC Prod cluster. 

Let's include documentation as a part of this effort.

**Comment by yalturmes** [comment]
* Jenkins for RDPC prod has been successfully configured. 
  URL: https://jenkins.rdpc.cancercollaboratory.org/
  **Note:** RDPC dev configuration (yamls and helm values) was taken as a base template for setting up prod cluster and include RBAC tweaks necessary for Jenkins agent.
  **Note:** Helm value "master.fsGroup: 1000" has been added in order to address a container filesystem access issue that has been encountered during setup. Somehow this value wasn't necessary for RDPC dev configuration. Flagging this for further investigation in order to ensure uniform setup across dev/prod environments.

* Jenkins user accounts have been set up and provided credentials for the following team members:
  @henro001 @andricDu @lepsalex @yalturmes 

* All changes have been pushed to argo infra repo (https://github.com/OICR/argo-infra)
  Pull request (https://github.com/OICR/argo-infra/pull/301) approved and merged to master.

**Comment by yalturmes** [comment]
Additional investigation has been made to determine ownership configuration between RDPC dev and prod jenkins installations.
Looks like there is a difference in ownership inside /var/jenkins_home.
On RDPC-dev:
User: jenkins (1000) / Group: daemon (1)
On RDPC-prod:
User: jenkins (1000) / Group: jenkins (1000)

**Note:** 
Flagging this to discuss the remedy plan and plan to apply the necessary changes.
It might also make sense to extend the scope of task in order to include helm chart upgrade testing.
