### ISSUE TITLE
Contact page issue

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/roadmap#475]
UPDATE: the contact form isn't working at all now. Figured we can use this ticket, but it could be the connection to help desk/JIRA.

Amber received a tweet about it.

When testing, please be sure to try the OICR email addresses

## details from Christina:

See https://drive.google.com/file/d/1jQ3nln5pClw36bZN7TDhzxKdAHVwtfJE/view?usp=sharing

To reproduce:
1. Use the long OICR email address -> error (known issue)
2. Use different email addresses which are supposed to be acceptable (short OICR email address, Gmail, other email) -> still return error
3. Click "Send message" many times until the captcha expires.
4. Try again with any of the emails in #2.  The message can now be sent succesfully.

Options:

**Comment by kcullion** [comment]
de-prioritized in Dan's queue and we can discuss in the new year about the process of allowing dcc admin access in prod

**Comment by demariadaniel** [comment]
@samrichca found errors were related to failed calls to https://extsd.oicr.on.ca/rest/servicedeskapi

@atulkachru reached out to IT service desk as we do not know who manages this endpoint.

They suggested "At first glace, if you are simply getting that error hitting that page, I would think the "token" might have expired, and you might have to re-generate a one."

My OICR & personal email accounts are unable to generate an API token in prod. So I am unable to validate this. Will resume in the new year.

**Comment by kcullion** [comment]
@joneubank fixed the contact form!

And the case reported by Christina is an edge case, if someone uses their full OICR email address that is part of the JIRA user group - they can't create a ticket, it is a known bug with jira https://jira.atlassian.com/browse/JSDCLOUD-6061

They will have to use another email address. If we have someone at OICR contact us with this issue, we can then look into allowing usernames into the argo form, but this is an extreme edge case for now. 

Thanks @joneubank !! closing this issue because it was handled on the JIRA side.
