### ISSUE TITLE
Orchestration Service Diagram 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#503]
Create a service architecture diagram and sequence diagram showing: 
- which architectural components will be needed for workflow orchestration 

- the sequence of events from SONG publish all the way to VCF through the service architecture

**Comment by lepsalex** [comment]
Initial UML Sequence diagram for review attached. Moving ticket to code review, once finalized will put into wiki.

![Workflow Automation S-UML.png](https://images.zenhubusercontent.com/5bbcc26ba9a60b5456b2cac2/fc7a7826-458c-48fc-8af7-4441f9e9e93e)

**Comment by lepsalex** [comment]
Basically the same thing except cutting out one of the services so that we only have what I am calling "Workflow Graph". There are two entities in this system, workflows (nodes) and activation functions (edges), the nodes are consumers of a `$WF-NAME.start` topic (where this name is configured in the workflow setup), and edges are consumers of `SONG.Publish` with an event filter (configurable to analysis type for example) and producers on a `$WF-NAME.start` topic (configured in the edge setup).

To start this can be a monolith but I think this approach lends itself well to lambda architecture, tbd I guess ...

![Workflow Automation S-UML.png](https://images.zenhubusercontent.com/5bbcc26ba9a60b5456b2cac2/2fb2d9b8-7eb3-48b0-8b7a-cd37f51b30a7)

**Comment by lepsalex** [comment]
OK. Updated once more and an additional diagram to explain the data flow through the new Workflow Graph service.

![Workflow Automation UML Sequence Diagram.png](https://images.zenhubusercontent.com/5bbcc26ba9a60b5456b2cac2/724132cc-cfea-438d-a72f-03b1c724ab6a)

![Workflow Graph Data Flow.png](https://images.zenhubusercontent.com/5bbcc26ba9a60b5456b2cac2/46731f13-30ea-4898-be77-476e2fbcd1d3)

**Comment by lepsalex** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Worfklow+Graph+Design

Such improvement. Much wow. Thank you to @rosibaj and @andricDu for all the time going back and forth on this with me.
