### ISSUE TITLE
RDPC: Testing K8s rolling restarts do not cause downtime

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#524]
We want to confirm that rolling restarts for the following services will not result in any downtime of the system, mostly importantly that they do not affect the running workflows:

- song     
- workflow-management     
- workflow-search     
- workflow-relay - relay-weblog     
- workflow-relay - relay-splitter     
- workflow-relay - relay-index     
- workflow-ui     
- workflow-docs     
- workflow-gateway     
- rdpc-status     
- rdpc-gateway     
- maestro     
- score     
- intermediate-song     
- Song-search

Test rolling restart for all services in an environment that is running workflows in DEV/QA
- Clear dev of data
- Run a workflow that runs forever or for a long period of time. Alexis built one like this to test her Cancel endpoint. 
- While workflows are continuously running, kickoff continuous rolling restarts on all services. Leave this running for a long period of time (days?).
- Check pass/fail criteria

Suggested pass/fail criteria:
- Look at task log outputs, they are numbered. We can determine if we lost data. 
- Or find a completed workflow that has a non-completed task

**Comment by yalturmes** [comment]
**DIscussion:**
**Core services for workflow:**
song  - cannot be taken down if workflow utilizes it
score  - cannot be taken down if workflow utilizes it
intermediate-song  - cannot be taken down if workflow utilizes it
workflow-relay - relay-weblog  - cannot be taken down if workflow utilizes it

**Non-essential services that can be restarted:**
workflow-management  - can be redeployed when workflow is running
workflow-search  -can be redeployed when workflow is running
workflow-relay - relay-splitter  - can be redeployed when workflow is running
workflow-relay - relay-index  - can be redeployed when workflow is running
workflow-ui  - can be redeployed when workflow is running
workflow-docs  - can be redeployed when workflow is running
workflow-gateway  - can be redeployed when workflow is running
rdpc-status  - can be redeployed when workflow is running
rdpc-gateway  - can be redeployed when workflow is running
maestro  - can be redeployed when workflow is running
Song-search - can be redeployed when workflow is running

**Comment by yalturmes** [comment]
After a discussion with Alex and Alexis it has been identified that prior to testing rolling restarts for RDPC services, it is necessary to take care of the following pre-reqs:
* Audit RDPC services helm charts to ensure they include liveness/readiness probes against `/actuator/health` endpoint for relevant deployments/statefulsets
* Review, discuss and establish which health checks necessary for each rdpc service
* Implement actuator health checks identified in the previous step for each rdpc service

Once the pre-requisites have been resolved, the testing activities will likely involve attempts to artificially introduce actuator health check failure rather than bulk redeployment approach initially suggested for this ticket activities.

Closing as not relevant anymore.
