### ISSUE TITLE
Central File Metadata specification 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#544]
- [ ] central system across all songs to track information for release 
- [ ] needs to associate a file with its tags for the release job
- [x] Investigate the Ga4GH DRS specification and understand the overlap with FileID Requirements.  Should we implement a File ID based on DRS specifications? 
 https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/#_drs_ids

#Exit Criteria 
- wiki page with technical architecture/analysis

**Comment by blabadi** [comment]
from reading the DRS specs, it's song and score that fit as DRS services, not the file id service. DRS goal is to unify the API (RESTful one) which data consumers talk to, in order to discover how (http, ftp, s3) and where (urls) the actual files live.
our overture song has its own API to explore and fetch data objects metadata and authorise then download actual files by going to score, so thats where DRS comes in to use their standard api

**Comment by blabadi** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Federated+Files+ID+Service

**Comment by blabadi** [comment]
@rosibaj  not sure who wants to review, the link in the comment above
