### ISSUE TITLE
Test multi-score interaction with k8s secrets

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#554]
- [x]  Test download from icgc score and upload to rdpc qa score in one workflow (verify secret management with different api tokens)
- [x] Edit model T to not pass API keys

**Comment by lepsalex** [comment]
* with the current setup, and any future setup, we only really want to support a single ego ... therefore in order to use a different API token you will just pass it in like you did in previous workflow runs
  * intermediate song/score is an exception not the rule so putting in a bunch of stuff to handle this when we have a working solution doesn't make sense at this time
  * this is also good because it maintains backwards compatibility
* model-tee does not need to be "updated", rather we will just update the run config to pass no token (except the score one) and the workflows will use the mounted secret for the processes where the token parameter was not provided (upload for now)
