### ISSUE TITLE
[Kafka Backups] Create and deploy Kafka connect helm chart (streaming replication)

### ISSUE THREAD

**Issue by henro001** [icgc-argo/roadmap#669]
- Create and test Kafka connect helm chart
- Deploy -

- [x] RDPC DEV
- [x] RDPC QA
- [x] RDPC PROD

**Comment by akachru-github** [comment]
Update on scope: 
- assumed bitnami charts supported extra deployment, but we are using a very old verison of the chart. because of this the deploying of kafka connect will not be integrated with the kafka chart, we will be building a new chart for kafka connect. 
- running two solutions: 
-- one is a replication to a filesystem, streaming to a file. This will roll over based on time. Once a month initial agreement.  
-- one is a scheduled backup / dump. Daily. 

Kakfa connect dedicated chart is almost ready. Next steps to deploy into DEV / QA.
