### ISSUE TITLE
-DO NOT USE- Covid-19 Data Portal Spin up

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#743]
End Goal: 
![image](https://user-images.githubusercontent.com/15824252/111687572-cca9f500-8800-11eb-89d0-47ae355cbc30.png)
![image](https://user-images.githubusercontent.com/15824252/111687611-d59ac680-8800-11eb-93fb-0776e67801d9.png)

Wiki: https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal

Org: https://github.com/cancogen-virus-seq

**Comment by akachru-github** [comment]
Proposal - 

**1 month demo**
- minimized deployed (single VM)
- include below new features as part of demo. 

**Development work**
- New features:
  - UI on song and score (Alex)
  - Institutional email support (Jaser on investigate keycloak)
  - Convert TSV to JSON (Dusan / Alex)
- Other
  - Styling of DMS UI (Justin)
  - Data population

**Unknowns**
- Will Quebec Openstack be hosting just the data, or the entire application stack? If the entire stack, we should get the devops team an orientation of their Openstack instance sooner rather than alter so we can start planning for prod deploy.
