### ISSUE TITLE
🐛 Production facets values aren't coming through

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#798]
## Describe the bug
Please fix the facet panel in production and report on why this problem is happening
![image](https://user-images.githubusercontent.com/18424138/118998815-bed73400-b957-11eb-86d2-066a0b5862fe.png)

**Comment by rosibaj** [comment]
@joneubank Before I close this i would like to get to the root of this problem. Can you please record what happened on this ticket when you figure it out?

**Comment by joneubank** [comment]
Can confirm that the index wasnt ever changed, it has always had the new `release_state`/`embargo_stage` properties in the mapping, replacing the `release_stage` property from release_2.0 index.

However, the platform-api had not been restarted after the new indices were aliased. @blabadi confirmed that the platform-api was restarted in both staging and prod within the last 24 hours. When restarted, the arranger GQL schema is regenerated from the index mapping.

When the arranger schema updated, the old prop was removed. The UI was requesting this property when fetching the facets, even though the UI was never using the data returned for this property. The result was no facets showing.

The fix was to remove the reference to the `release_stage` property in the facet data request.

Going forward we need to restart the API after deploying an index with a new mapping. Alternately, we need a way to regenerate the arranger schema without a restart (this may be doable in arranger but I haven't looked for this in some time). By doing this in lower environments we can confirm if there are discrepancies between the UI GQL requests and the generated API, thus preventing issues resulting from updating the mapping in prod.

**Comment by rosibaj** [comment]
@joneubank do we know why prod api was restarted?

**Comment by joneubank** [comment]
No, but there are lots of potential reasons. It's not recorded who initiates restart. Might've just been by kubernetes managing resources even.
