### ISSUE TITLE
Intermediate Song Import

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#823]
- Need to import to `intermediate song` three donors from OCCAMS-GB and 8 donors from LUCA-KR.
- these donors needed additional data transfers that had been blocked until recently by an indexing issue
- Payloads to be imported cover these 3 issues: 
  - https://github.com/icgc-argo/argo-meta/issues/32
  - https://github.com/icgc-argo/ega-file-transfer/issues/12
  - https://github.com/icgc-argo/ega-file-transfer/issues/10

link to payloads to be imported: 

OCCAMS-GB:
3 WGS donors: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/OCCAMS-GB/WGS/batch4-wgs

LUCA-KR:
1 WGS donor: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/LUCA-KR/WGS/batch2
7 WXS donors: https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/LUCA-KR/WXS/batch3

wiki: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by hknahal** [comment]
Jon completed the data import for these SONG payloads, but a few files generated file duplication errors, indicating the data is already present in ARGO. I reviewed the intermediate-song logs ([LUCA-KR WXS log](https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/LUCA-KR/WXS/intermediate-song-rdpc-collab-report.LUCA-KR-WXS.batch3.json) and [WGS log](https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/LUCA-KR/WGS/intermediate-song-rdpc-collab-report.LUCA-KR.WGS.batch2.json), and [OCCAMS-GB WGS log](https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/OCCAMS-GB/WGS/intermediate-song-rdpc-collab-report.WGS.batch4.json)) to confirm why this happened. 

LUCA-KR: It appears the files that generated a file duplication error were all 'Normal' samples, which already exist in ARGO from a previous data import. But the files related to the matching 'Tumour' sample were the ones missing in ARGO, and these files got imported over okay. I generated the 'Normal' sample SONG payloads because they were required when validating the tumour SONG payloads, but they were mistakenly included in these batches. We only needed to import the files related to the 'Tumour' samples. We can safely ignore these file duplication errors.

OCCAMS-GB: The same applies here. The file generating the file duplication error (see log [here](https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/OCCAMS-GB/WGS/intermediate-song-rdpc-collab-report.WGS.batch4.json)) was imported to ARGO during a previous data import. We can safely ignore this file duplication error.
