### ISSUE TITLE
Identify of problematic upgrades to support critical and high security alerts: Platform-UI

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#858]
Some of the upgrades are causing pipeline issues: https://github.com/icgc-argo/platform-ui/issues/2122

- [ ] yup
- [ ] ... more

**Comment by demariadaniel** [comment]
Npm Audit Fix breaks Storybook, because many of our main vulnerabilities are in Storybook

But the change from 6.0.22 -> 6.4.9 appears to be significant, and was breaking both the pipeline and local Storybook

Many vulnerabilities are currently patched by #2122 using `npm-force-resolutions` but can by fixed by updating Next.js, Storybook, and Emotion, all of which are breaking changes

 Storybook
	prismjs
	react-dev-utils
	ssri
	y18n
	ini
	Storybook Knobs has been deprecated for Storybook Controls, requires _many_ component updates

Next.js
	Open Redirect in Next.js
	Unexpected server crash in Next.js
	tar
	object-path

Emotion
        10 > 11 includes breaking alias change requiring updates to `.storybook/webpack.config.js`
