### ISSUE TITLE
Evaluate whether an ES upgrade is necessary

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#881]
- Current version?
- Are we in support? Will we be out of support soon?
- Audit all environments. Output will be a table within this ticket.

**Comment by Buwujiu** [comment]
Audited these following environments:
ARGO qa/dev
1.  Current version: 7.6
2. Already out of support, see https://www.elastic.co/support/eol, 7.6 is supported until 2021-08-11

RDPC dev/qa/prod
1. Current Version: 7.6
2. Already out of support, see https://www.elastic.co/support/eol, 7.6 is supported until 2021-08-11

Overture qa/staging
1. Current version: 7.6
2. Already out of support, see https://www.elastic.co/support/eol, 7.6 is supported until 2021-08-11

**Comment by akachru-github** [comment]
Let's identify: 
- latest supported version
- potential breaking changes for the upgrade

**Comment by Buwujiu** [comment]
1. The latest supported versions are: ![Screen Shot 2022-04-07 at 4.16.09 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/e882f932-cf62-4d60-a1e0-d0b9eee8d48b)
2. In order to upgrade to 8.1.2 which is the latest version, we must first upgrade to 7.17 as suggested by ES: https://www.elastic.co/guide/en/elastic-stack/8.1/upgrading-elastic-stack.html#prepare-to-upgrade.
3. Breaking changes of 7.17: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/migrating-7.17.html#breaking-changes-7.17

**Comment by Buwujiu** [comment]
Organized output to this wiki: https://wiki.oicr.on.ca/display/icgcargotech/ES+Upgrade
