### ISSUE TITLE
Investigation on How to Run WF in Azure

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#975]
## Detailed Description
Step 1 - Run a Hello world WF in Azure cluster. 
Step 2 - Run an actual WF  - alignment wf in Azure. 

## Challenge
- Azure has its own config, need to learn.
- Learning how nextflow works.

## Exit Criteria
- POC and wiki the investigation results.

**Comment by UmmulkiramR** [comment]
Could kick off a hello world workflow in the azure cluster, however the pods could not get running due to the absence of the Persistent Volumes(PV) and the Persistent Volume Claims(PVC) on the azure cluster. In the absence of the PVs and PVCs no workflows will get triggered as the Nexftlow library will not allow it. 

Need the help from the devops team to have these setup in order to proceed.

**Comment by UmmulkiramR** [comment]
After the PVs and PVCs were created jobs could be triggered to the azure cluster through management running locally. Hello-world worked, Dna-Seq worked too.  However, Dna-Seq jobs do not complete due to some stuff that needs to be made available still.

**Current issue when running Dna-Seq jobs:**
Secret creation fails. Probably some access problem.  

**Things we need to check/work on next (as identified so far):**
1. Have workflows access song and score. This is possible as song and score are public.
2. Have workflows access relay-weblog to relay the real -time status of the workflows to management.  Relay-weblog is not a public service and we'll not be converting it to one. Instead we would provide a means (probably some kind of rights) for Azure to access weblog


**Biggest challenges:**
1. Authentication between Collab open stack and the azure cluster. The current service account token mechanism would not work for this. Some other auth mechanism would have to be employed here.
2. Means to make azure’s kube context information available to nextflow commands running in collab. 

@henro001 pls confirm.

**Comment by UmmulkiramR** [comment]
Dna-seq workflow successfully completes in Azure.
